language: node_js

services:
  - redis-server

node_js:
  - "stable"

script:
  - npm run reporter
  - npm run e2e
  - npm run specs

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
